include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-casts: false
    strict-raw-types: true
  errors:
    invalid_assignment: warning
    missing_return: error
    dead_code: info

linter:
  rules:
    - cancel_subscriptions: true
    - always_use_package_imports: true
    - avoid_types_as_parameter_names: true
    - avoid_web_libraries_in_flutter: true
    - invalid_case_patterns: true
    - no_duplicate_case_values: true
    - avoid_dynamic_calls: true
    - avoid_print: true
    - prefer_single_quotes: true
    - always_declare_return_types: true
    - annotate_overrides: true
    - avoid_returning_null_for_void: true
    - avoid_void_async: true
    - camel_case_extensions: true
    - camel_case_types: true
    - file_names: true
    - prefer_if_null_operators: true
    - await_only_futures: true

