name: melonkemo
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  rive: ^0.10.3
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
  - assets/rive/
  fonts:
    - family: KosugiMaru
      fonts:
        - asset: fonts/kosugi_maru_regular.ttf
    - family: Itim
      fonts:
        - asset: fonts/itim_regular.ttf
