name: melonkemo
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dartx: ^1.2.0
  uuid: ^4.2.2
  flutter_animate: ^4.2.0+1
  cupertino_icons: ^1.0.6
  collection: ^1.17.2
  rive: ^0.11.17
  auto_size_text: ^3.0.0
  provider: ^6.0.5
  go_router: ^11.1.2
  shared_preferences: ^2.2.1
  dio: ^5.3.3
  flutter_secure_storage: ^9.0.0
  bot_toast: ^4.1.3
  flutter_spinkit: ^5.2.0
  layout: ^1.0.5
  fluid_dialog: ^2.0.0
  pull_down_button: ^0.9.3
  adaptive_action_sheet: ^2.0.2
  modal_bottom_sheet: ^3.0.0-pre
  url_launcher: ^6.2.1
  file_picker: ^6.0.0
  demoji: ^2.0.0
  simple_icons: ^7.10.0
  scrollable_positioned_list: ^0.3.8
  wolt_modal_sheet: ^0.4.1
  shimmer: ^3.0.0
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
  - assets/rive/
  - assets/images/
  - assets/icons/

  fonts:
    - family: KosugiMaru
      fonts:
        - asset: fonts/kosugi_maru_regular.ttf
    - family: VarelaRound
      fonts:
        - asset: fonts/VarelaRound-Regular.ttf
    - family: Itim
      fonts:
        - asset: fonts/itim_regular.ttf
    - family: MochiyPopOne
      fonts:
        - asset: fonts/mochiy_pop_one_regular.ttf
    - family: Sarabun
      fonts:
        - asset: fonts/sarabun/Sarabun-Thin.ttf
          weight: 200
        - asset: fonts/sarabun/Sarabun-ExtraLight.ttf
          weight: 300
        - asset: fonts/sarabun/Sarabun-Light.ttf
          weight: 400
        - asset: fonts/sarabun/Sarabun-Regular.ttf
          weight: 500
        - asset: fonts/sarabun/Sarabun-Medium.ttf
          weight: 600
        - asset: fonts/sarabun/Sarabun-Bold.ttf
          weight: 700
        - asset: fonts/sarabun/Sarabun-ExtraBold.ttf
          weight: 800
    - family: Mali
      fonts:
        - asset: fonts/mali/Mali-ExtraLight.ttf
          weight: 300
        - asset: fonts/mali/Mali-Light.ttf
          weight: 400
        - asset: fonts/mali/Mali-Regular.ttf
          weight: 500
        - asset: fonts/mali/Mali-Medium.ttf
          weight: 600
        - asset: fonts/mali/Mali-Bold.ttf
          weight: 700
    - family: MPlus
      fonts:
        - asset: fonts/m_plus_rounded/MPLUSRounded1c-Thin.ttf
          weight: 300
        - asset: fonts/m_plus_rounded/MPLUSRounded1c-Light.ttf
          weight: 400
        - asset: fonts/m_plus_rounded/MPLUSRounded1c-Regular.ttf
          weight: 500
        - asset: fonts/m_plus_rounded/MPLUSRounded1c-Medium.ttf
          weight: 600
        - asset: fonts/m_plus_rounded/MPLUSRounded1c-Bold.ttf
          weight: 700

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/icons/web_icon.png"