name: melonkemo
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  rive: ^0.11.3
  auto_size_text: ^3.0.0
  provider: ^6.0.5
  go_router: ^8.1.0
  shared_preferences: ^2.1.2
  dio: ^5.2.1+1
  flutter_secure_storage: ^8.0.0
  bot_toast: ^4.0.4
  flutter_spinkit: ^5.2.0
  layout: ^1.0.3
  fluid_dialog: ^1.1.1
  pull_down_button: ^0.9.1
  adaptive_action_sheet: ^2.0.2
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
  - assets/rive/
  fonts:
    - family: KosugiMaru
      fonts:
        - asset: fonts/kosugi_maru_regular.ttf
    - family: Itim
      fonts:
        - asset: fonts/itim_regular.ttf
    - family: MochiyPopOne
      fonts:
        - asset: fonts/mochiy_pop_one_regular.ttf
    - family: Sarabun
      fonts:
        - asset: fonts/sarabun/Sarabun-Thin.ttf
          weight: 200
        - asset: fonts/sarabun/Sarabun-ExtraLight.ttf
          weight: 300
        - asset: fonts/sarabun/Sarabun-Light.ttf
          weight: 400
        - asset: fonts/sarabun/Sarabun-Regular.ttf
          weight: 500
        - asset: fonts/sarabun/Sarabun-Medium.ttf
          weight: 600
        - asset: fonts/sarabun/Sarabun-Bold.ttf
          weight: 700
        - asset: fonts/sarabun/Sarabun-ExtraBold.ttf
          weight: 800
    - family: Mali
      fonts:
        - asset: fonts/mali/Mali-ExtraLight.ttf
          weight: 300
        - asset: fonts/mali/Mali-Light.ttf
          weight: 400
        - asset: fonts/mali/Mali-Regular.ttf
          weight: 500
        - asset: fonts/mali/Mali-Medium.ttf
          weight: 600
        - asset: fonts/mali/Mali-Bold.ttf
          weight: 700
    - family: MPlus
      fonts:
        - asset: fonts/m_plus_rounded/MPLUSRounded1c-Thin.ttf
          weight: 300
        - asset: fonts/m_plus_rounded/MPLUSRounded1c-Light.ttf
          weight: 400
        - asset: fonts/m_plus_rounded/MPLUSRounded1c-Regular.ttf
          weight: 500
        - asset: fonts/m_plus_rounded/MPLUSRounded1c-Medium.ttf
          weight: 600
        - asset: fonts/m_plus_rounded/MPLUSRounded1c-Bold.ttf
          weight: 700
